"""table name change

Revision ID: 030c0ca6022b
Revises: fde953f516ae
Create Date: 2024-04-08 00:31:03.112470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030c0ca6022b'
down_revision = 'fde953f516ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('total_paid', sa.Integer(), nullable=False),
    sa.Column('monday', sa.String(length=256), nullable=False),
    sa.Column('tuesday', sa.String(length=256), nullable=False),
    sa.Column('wednesday', sa.String(length=256), nullable=False),
    sa.Column('thursday', sa.String(length=256), nullable=False),
    sa.Column('friday', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_timestamp')
        batch_op.drop_index('ix_order_user_id')

    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=256), nullable=False),
    sa.Column('total_paid', sa.INTEGER(), nullable=False),
    sa.Column('monday', sa.VARCHAR(length=256), nullable=False),
    sa.Column('tuesday', sa.VARCHAR(length=256), nullable=False),
    sa.Column('wednesday', sa.VARCHAR(length=256), nullable=False),
    sa.Column('thursday', sa.VARCHAR(length=256), nullable=False),
    sa.Column('friday', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index('ix_order_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_order_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_timestamp'))

    op.drop_table('orders')
    # ### end Alembic commands ###
