"""one to one

Revision ID: 424f496b0e53
Revises: b7fe2a0a7bec
Create Date: 2024-02-25 18:18:13.848310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424f496b0e53'
down_revision = 'b7fe2a0a7bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_user_id')
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_user_id'))
        batch_op.create_index('ix_order_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
