"""update orders data model

Revision ID: b7fe2a0a7bec
Revises: dbbcb264aace
Create Date: 2024-02-25 17:15:16.522079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fe2a0a7bec'
down_revision = 'dbbcb264aace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('tuesday', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('wednesday', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('thursday', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('friday', sa.String(length=256), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.VARCHAR(length=512), nullable=False))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('friday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('wednesday')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('monday')

    # ### end Alembic commands ###
